services:
  wedding_app:
    image: postgres:15
    hostname: wedding_app
    container_name: wedding_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wedding_app}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5556:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
volumes:
  postgres-data: