/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeatMapEditorRouteImport } from './routes/seat-map-editor'
import { Route as IndexRouteImport } from './routes/index'

const SeatMapEditorRoute = SeatMapEditorRouteImport.update({
  id: '/seat-map-editor',
  path: '/seat-map-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seat-map-editor': typeof SeatMapEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seat-map-editor': typeof SeatMapEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seat-map-editor': typeof SeatMapEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seat-map-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seat-map-editor'
  id: '__root__' | '/' | '/seat-map-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeatMapEditorRoute: typeof SeatMapEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seat-map-editor': {
      id: '/seat-map-editor'
      path: '/seat-map-editor'
      fullPath: '/seat-map-editor'
      preLoaderRoute: typeof SeatMapEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeatMapEditorRoute: SeatMapEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
